/* Generated By:JavaCC: Do not edit this line. ControllerFSMFactoryConstants.java */
package com.lcsc.hackathon.kinectcontroller.config;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ControllerFSMFactoryConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STARTING_STATE = 1;
  /** RegularExpression Id. */
  int IS = 2;
  /** RegularExpression Id. */
  int VERSION = 3;
  /** RegularExpression Id. */
  int STATE = 4;
  /** RegularExpression Id. */
  int GESTURE = 5;
  /** RegularExpression Id. */
  int MOUSE_GESTURE = 6;
  /** RegularExpression Id. */
  int RULE = 7;
  /** RegularExpression Id. */
  int REACTION = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int VERTEX = 10;
  /** RegularExpression Id. */
  int MIN_ANGLE = 11;
  /** RegularExpression Id. */
  int MAX_ANGLE = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"starting_state\"",
    "\"is\"",
    "\"version\"",
    "\"state\"",
    "\"gesture\"",
    "\"gesture mouse using\"",
    "\"rule\"",
    "\"reaction\"",
    "\"end\"",
    "\"vertex\"",
    "\"min_angle\"",
    "\"max_angle\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 19>",
  };

}
